CREATE TABLE IF NOT EXISTS likes (
	id VARCHAR(75) PRIMARY KEY,
    source VARCHAR(25) NOT NULL,
    source_id VARCHAR(255) NOT NULL,
    refer VARCHAR(255) NOT NULL,
    raw_url VARCHAR(255) NOT NULL,
   	fetch_at DATETIME NOT NULL
) ENGINE=INNODB;

